### ISSUE TITLE
no spaces around mdjrny-v4 prompt.

### ISSUE THREAD

**Issue by kdemarest** [shamspias/chatgpt-voice-chatbot-telegram#1]
Did you intend to have no spaces here? Perhaps you inject them into prompt first? 

'prompt': "mdjrny-v4 style" + prompt + "4k resolution",

**Comment by shamspias** [comment]
Thanks for letting me know that

I will add space and the prompt should be in the middle instead of 1st because fore replicated API need use mdjrny-v4 style at 1st
